name: WDBReader CI build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:

    # Checkout WDBReader
    - uses: actions/checkout@v4
      with:
        path: wdbreader
    
    #casclib
    - uses: actions/checkout@v4
      with:
        repository: ladislav-zezula/CascLib
        path: deps/casclib

    - name: build casclib
      run: |
        cd ${{ github.workspace }}/deps/casclib
        mkdir build
        mkdir install
        cmake -S . -B ./build -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=./install -DCASC_BUILD_SHARED_LIB=OFF -DCASC_BUILD_STATIC_LIB=ON -DCASC_UNICODE=ON
        cmake --build ./build --config Debug
        cmake --build ./build --config Release
        cmake --install ./build --config Debug --prefix ./install
        cmake --install ./build --config Release --prefix ./install

    #stormlib
    - uses: actions/checkout@v4
      with:
        repository: ladislav-zezula/StormLib
        path: deps/stormlib

    - name: build stormlib
      run: |
        cd ${{ github.workspace }}/deps/stormlib
        mkdir build
        mkdir install
        cmake -S . -B ./build -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=./install
        cmake --build ./build --config Debug
        cmake --build ./build --config Release
        cmake --install ./build --config Debug --prefix ./install
        cmake --install ./build --config Release --prefix ./install

    #catch2
    - uses: actions/checkout@v4
      with:
        repository: catchorg/Catch2
        path: deps/catch2

    - name: build catchorg/Catch2
      run: |
        cd ${{ github.workspace }}/deps/catch2
        mkdir build
        mkdir install
        cmake -S . -B ./build -DCMAKE_INSTALL_PREFIX=./install
        cmake --build ./build --config Debug
        cmake --install ./build --config Debug --prefix ./install

    #WDBReader
    - name: build wdbreader prep
      run: |
        cd ${{ github.workspace }}/wdbreader
        mkdir build
        mkdir install

    - name: build wdbreader debug
      run: |
        cd ${{ github.workspace }}/wdbreader
        cmake -S . -B ./build -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=./install -DBUILD_TESTING=ON -DBUILD_APPS=ON \
          -DCatch2_DIR=${{ github.workspace }}/deps/catch2/install/lib/cmake/Catch2 \
          -DCascLib_DIR=${{ github.workspace }}/deps/casclib/install/lib/cmake/CascLib \
          -DStormLib_DIR=${{ github.workspace }}/deps/stormlib/install/share/StormLib \
        cmake --build ./build --config Debug

    - name: test wdbreader debug
      run: |
        ctest --output-on-failure --test-dir ${{ github.workspace }}/wdbreader/build

    - name: build wdbreader release
      run: |
        cd ${{ github.workspace }}/wdbreader
        cmake -S . -B ./build -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=./install -DBUILD_TESTING=OFF -DBUILD_APPS=ON \
          -DCatch2_DIR=${{ github.workspace }}/deps/catch2/install/lib/cmake/Catch2 \
          -DCascLib_DIR=${{ github.workspace }}/deps/casclib/install/lib/cmake/CascLib \
          -DStormLib_DIR=${{ github.workspace }}/deps/stormlib/install/share/StormLib \
        cmake --build ./build --config Release

    - name: build wdbreader package
      run: |
        cd ${{ github.workspace }}/wdbreader  
        cmake --install ./build --config Debug --prefix ./install
        cmake --install ./build --config Release --prefix ./install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: $GITHUB_WORKSPACE/wdbreader/install
        name: WDBReader